version: '2'

services:

  ferretdb-postgresql:
    image: ghcr.io/ferretdb/all-in-one
    restart: on-failure
    ports:
      - 27010:27017
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8

  ferretdb-sqlite:
    image: ghcr.io/ferretdb/all-in-one
    restart: on-failure
    ports:
      - 27011:27017
    environment:
      - FERRETDB_HANDLER=sqlite
      - FERRETDB_SQLITE_URL=file:/data/
      - DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8
    volumes:
      - ./data:/data/

volumes:
  data:
    driver: local

networks:
  wekan-tier:
    driver: bridge
