services:

#  ferretdb-postgresql:
#    image: ghcr.io/ferretdb/all-in-one
#    restart: on-failure
#    ports:
#      - 27010:27017
#    environment:
#      - DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8
#      - FERRETDB_REPL_SET_NAME=rs0
#
#  ferretdb-postgresql-setup:
#    image: ghcr.io/ferretdb/all-in-one
#    restart: no
#    depends_on:
#      - ferretdb-postgresql
#    entrypoint: [ "bash", "-c", "sleep 10 && /usr/bin/mongosh --host ferretdb-postgresql:27010 --eval 'use local;db.createCollection('oplog.rs', { capped: true, size: 536870912 });'"]

  ferretdb-sqlite:
    image: ghcr.io/ferretdb/all-in-one
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_HANDLER=sqlite
      - FERRETDB_SQLITE_URL=file:/data/
      - DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8
      - FERRETDB_REPL_SET_NAME=rs0
    volumes:
      - ./data:/data/

  ferretdb-sqlite-setup:
    image: ghcr.io/ferretdb/all-in-one
    restart: no
    depends_on:
      - ferretdb-sqlite
    entrypoint: [ "bash", "-c", "sleep 10 && /usr/bin/mongosh --host ferretdb-sqlite:27017 --eval 'use local;db.createCollection('oplog.rs', { capped: true, size: 536870912 });'"]

volumes:
  data:
    driver: local

networks:
  wekan-tier:
    driver: bridge
